---
- name: variables
  hosts: localhost
  vars:
    course: Terraform
    Duration: 20Hrs
#- name: print variable at play level
#  ansible.builtin.debug:
#  msg: "I am learing DevOps from {{course}} and Duration is {{Duration}}, at play level"

  tasks:
    - name: print variable information
      ansible.builtin.debug:
        msg: "I am learing DevOps from {{course}} and Duration is {{Duration}}"