- name: data types
  hosts: localhost
  vars:
    Course: DevOps with AWS #string
    Tools:  #list
    - Linux
    - Shell
    - Ansible
    Experience: #map or dict
      DevOps: 3
      AWS: 2
      Docer: 1
    Realproject: true
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "Course: {{Course}}, Tools covered: {{Tools}}, Experience is {{Experience}}, is realtime project: {{Realproject}}"