- name: check the number and display the info
  hosts: localhost
  vars_prompt:
  - name: number
    prompt: enter number
    private: no

  tasks:
  - name: number greater than 10
    ansible.builtin.debug:
      msg: "Given number is > 10 "
    when: number | int > 10
  
  - name: number less than 10
    ansible.builtin.debug:
      msg: "Given number is < 10 "
    when: number | int < 10