- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: print loop items
    ansible.builtin.debug:
      msg: "{{item}}"
    loop:
    - linux
    - ansible
    - terroform
    - docker
  - name: Install packages
    ansible.builtin.dnf:
      name: "{{item}}"
    loop:
      - mysql
      - nginx
      - postfix